Send codecov report using bash script

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -80,9 +80,9 @@ jobs:
         run: docker exec prophet pytest --cov-report=xml --cov=./ -p no:warnings -vv
 
       - name: Upload coverage to Codecov
-        run: docker exec prophet bash <(curl -s https://codecov.io/bash) \
-          || echo 'Codecov failed to upload' \
-          -t ${{ secrets.CODECOV_PAT }}
+        run: docker exec prophet bash -c "bash <(curl -s https://codecov.io/bash)" \
+          -t ${{ secrets.CODECOV_PAT }} \
+          || echo 'Codecov failed to upload'
 
       - name: Flake8
         run: docker exec prophet python -m flake8 .
